#!/bin/bash +x

mount -t proc proc rootfs/proc
mount -t sysfs sys rootfs/sys
mount --bind /dev rootfs/dev
cat <<EOF | LANG=en_GB.UTF-8 LANGUAGE=en_GB.UTF-8 chroot rootfs/


cat > /etc/apt/sources.list <<EOFSRC
deb http://deb.debian.org/debian bullseye main contrib non-free
deb http://deb.debian.org/debian bullseye-updates main contrib non-free
deb http://deb.debian.org/debian bullseye-backports main contrib non-free
deb http://security.debian.org/debian-security/ bullseye-security main contrib non-free
EOFSRC



apt-get update

apt-get -y install locales

cat > /etc/locale.gen <<EOF1
en_GB ISO-8859-1
en_GB.ISO-8859-15 ISO-8859-15
en_GB.UTF-8 UTF-8
EOF1

cat > /etc/default/locale <<EOF2
LC_ALL=en_GB.UTF-8
LANG=en_GB.UTF-8
EOF2

locale-gen 
exit 0
EOF

umount rootfs/proc
umount rootfs/sys
umount rootfs/dev


exit 0
