#!/bin/bash
mount -t proc proc rootfs/proc
mount -t sysfs sys rootfs/sys
mount --bind /dev rootfs/dev
cat <<EOF | LANG=en_GB.UTF-8 LANGUAGE=en_GB.UTF-8 chroot rootfs/


apt-get -y   remove --purge  systemd



EOF
umount  rootfs/proc rootfs/sys rootfs/dev

exit 0
